apiVersion: v2
name: a3-group-g3-rbacher-jahutz #name of the app, this should be the project name, spaces should be substituted with -
description: My Example App #description for the app
type: application
version: 0.0.1 #for versioning of the helm chart, increase it when new release is built/deployed
appVersion: "0.0.1"